// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATLq2m9NKinxVMfBCrtjUQJnJyQIhaK8',
    appId: '1:207790315419:web:ab83f34397d04b8979733e',
    messagingSenderId: '207790315419',
    projectId: 'selftalk-f588d',
    authDomain: 'selftalk-f588d.firebaseapp.com',
    storageBucket: 'selftalk-f588d.firebasestorage.app',
    measurementId: 'G-668EY55P5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UJIGz4fF081cGDVee_0Od2ihai41hhM',
    appId: '1:207790315419:android:f101b4792329482f79733e',
    messagingSenderId: '207790315419',
    projectId: 'selftalk-f588d',
    storageBucket: 'selftalk-f588d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gQRiv1qKtF3hfHXAYdPKqiND_JGIEvI',
    appId: '1:207790315419:ios:0d6cf255b8e8e86f79733e',
    messagingSenderId: '207790315419',
    projectId: 'selftalk-f588d',
    storageBucket: 'selftalk-f588d.firebasestorage.app',
    iosBundleId: 'com.easyo.flutterSelfTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4gQRiv1qKtF3hfHXAYdPKqiND_JGIEvI',
    appId: '1:207790315419:ios:b7ca999901bb9f8579733e',
    messagingSenderId: '207790315419',
    projectId: 'selftalk-f588d',
    storageBucket: 'selftalk-f588d.firebasestorage.app',
    iosBundleId: 'com.example.selfTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATLq2m9NKinxVMfBCrtjUQJnJyQIhaK8',
    appId: '1:207790315419:web:c7bd58296b00eb6a79733e',
    messagingSenderId: '207790315419',
    projectId: 'selftalk-f588d',
    authDomain: 'selftalk-f588d.firebaseapp.com',
    storageBucket: 'selftalk-f588d.firebasestorage.app',
    measurementId: 'G-9HC6PPT99W',
  );

}